<?php
$this->css($this->assetModule('css/admin.css'));
$this->css($this->assetModule('script/system-ui.css', 'system'));
$this->jQuery('ui/jquery-ui.min.js');
?>
<div class="clearfix" id="tree-template">
    <div id="attribute-sort">
        <div class="attribute-field">
            <?php foreach ($list as $element) { ?>
                <div id="mod_<?php echo $this->escape($element['id']); ?>">
                    <div class="tree-item">
                        <div class="tree-item-header" style="cursor:move;">
                            <div class="col-md-8">
                                <strong><?php _e('Title'); ?></strong> :
                                <span> <?php echo $this->escape($element['title']); ?> </span>
                            </div>
                            <div class="col-md-2">
                                <strong><?php _e('Type'); ?></strong> :
                                <span> <?php echo $this->escape($element['type']); ?> </span>
                            </div>
                            <div class="col-md-2">
                                <a class="btn btn-link" title="<?php _e('Edit'); ?>"
                                   href="<?php echo $this->url('', ['action' => 'update', 'id' => $element['id']]); ?>"><i
                                            class="fa fa-edit"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $('#attribute-sort .attribute-field').sortable({
            update: function (event, ui) {
                var list = $(this).sortable('serialize');
                $.post("<?php echo $this->url('', ['action' => 'sort']); ?>", list);
            }
        });
    });
</script>