<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php _e('List of forms'); ?></h3>
    <?php if (!empty($list)) { ?>
    <table class="table table-striped table-bordered table-condensed">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Title'); ?></th>
            <th><?php _e('Start'); ?></th>
            <th><?php _e('End'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($list as $form) { ?>
            <?php
            if ($form['status'] == 1) {
                $labelIdClass = 'label-success';
            } else {
                $labelIdClass = 'label-warning';
            }
            ?>
            <tr>
                <td><span
                        class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($form['id']); ?></span>
                </td>
                <td><?php echo $this->escape($form['title']); ?></td>
                <td><?php echo $this->escape($form['time_start_view']); ?></td>
                <td><?php echo $this->escape($form['time_end_view']); ?></td>
                <td><?php echo $this->escape($form['type_view']); ?></td>
                <td>
                    <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                       href="<?php echo $this->url('', array('action' => 'update', 'id' => $form['id'])); ?>"><i
                                class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                    <a class="btn btn-primary btn-xs" title="<?php _e('Element'); ?>"
                       href="<?php echo $this->url('', array('action' => 'element', 'id' => $form['id'])); ?>"><i
                                class="fa fa-edit"></i> <?php _e('Element'); ?></a>
                    <a class="btn btn-success btn-xs" title="<?php _e('View'); ?>"
                       href="<?php echo $this->url('', array('action' => 'view', 'id' => $form['id'])); ?>"><i
                                class="fa fa-edit"></i> <?php _e('View'); ?></a>
                </td>
            </tr>
        <?php } ?>
    </table>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('You still didnt make any form, please make new one'); ?>
        </div>
    <?php } ?>
</div>