<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php _e('List of forms'); ?></h3>
    <?php if (!empty($list)) { ?>
        <table class="table table-striped table-bordered table-hover table-responsive-md table-sm mt-3">
            <tr class="text-center">
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Count'); ?></th>
                <th><?php _e('Start'); ?></th>
                <th><?php _e('End'); ?></th>
                <th><?php _e('Need register'); ?></th>
                <th><?php _e('Need review'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $form) { ?>
                <?php if ($form['status'] == 1) {
                    $labelIdClass = 'label-success';
                } else {
                    $labelIdClass = 'label-warning';
                } ?>
                <tr class="text-center">
                    <td>
                        <span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($form['id']); ?></span>
                    </td>
                    <td><?php echo $this->escape($form['title']); ?></td>
                    <td><?php echo $this->escape($form['count_view']); ?></td>
                    <td><?php echo $this->escape($form['time_start_view']); ?></td>
                    <td><?php echo $this->escape($form['time_end_view']); ?></td>
                    <td><?php echo $form['register_need'] ? __('Yes') : __('No'); ?></td>
                    <td><?php echo $form['review_action'] ? __('Yes') : __('No'); ?></td>
                    <td>
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary btn-sm dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-edit"></i> <?php _e('Manage'); ?>
                            </button>
                            <div class="dropdown-menu" role="menu">
                                <a class="dropdown-item" title="<?php _e('Edit'); ?>"
                                   href="<?php echo $this->url('', ['action' => 'update', 'id' => $form['id']]); ?>">
                                    <i class="fa fa-edit"></i> <?php _e('Edit'); ?>
                                </a>
                                <a class="dropdown-item" title="<?php _e('Element'); ?>"
                                   href="<?php echo $this->url('', ['action' => 'element', 'id' => $form['id']]); ?>">
                                    <i class="fa fa-edit"></i> <?php _e('Element'); ?>
                                </a>
                            </div>
                        </div>
                        <div class="btn-group">
                            <button type="button" class="btn btn-success btn-sm dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-eye"></i> <?php _e('View'); ?>
                            </button>
                            <div class="dropdown-menu" role="menu">
                                <a class="dropdown-item" title="<?php _e('View on admin side'); ?>"
                                   href="<?php echo $this->url('', ['action' => 'view', 'id' => $form['id']]); ?>">
                                    <i class="fa fa-eye"></i> <?php _e('View on admin side'); ?>
                                </a>
                                <a class="dropdown-item" title="<?php _e('View on front side'); ?>"
                                   href="<?php echo $form['formUrl']; ?>" target="_blank">
                                    <i class="fa fa-eye"></i> <?php _e('View on front side'); ?>
                                </a>
                            </div>
                        </div>
                        <div class="btn-group">
                            <button type="button" class="btn btn-warning btn-sm dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-eye"></i> <?php _e('Record'); ?>
                            </button>
                            <div class="dropdown-menu" role="menu">
                                <a class="dropdown-item" title="<?php _e('View Records'); ?>"
                                   href="<?php echo $this->url('', ['controller' => 'record', 'selectForm' => $form['id']]); ?>">
                                    <i class="fa fa-eye"></i> <?php _e('View Records'); ?>
                                </a>
                                <a class="dropdown-item" title="<?php _e('Export Records'); ?>"
                                   href="<?php echo $this->url('', ['controller' => 'record','action' => 'export', 'selectForm' => $form['id']]); ?>">
                                    <i class="fa fa-eye"></i> <?php _e('Export Records'); ?>
                                </a>
                            </div>
                        </div>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('You still didnt make any form, please make new one'); ?>
        </div>
    <?php } ?>
</div>
