<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php _e('List of forms'); ?></h3>
    <?php if (!empty($list)) { ?>
        <table class="table table-striped table-bordered table-hover table-responsive-md table-sm mt-3">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Count'); ?></th>
                <th><?php _e('Start'); ?></th>
                <th><?php _e('End'); ?></th>
                <th><?php _e('Need register'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $form) { ?>
                <?php if ($form['status'] == 1) {
                    $labelIdClass = 'label-success';
                } else {
                    $labelIdClass = 'label-warning';
                } ?>
                <tr>
                    <td>
                        <span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($form['id']); ?></span>
                    </td>
                    <td><?php echo $this->escape($form['title']); ?></td>
                    <td><?php echo $this->escape($form['count_view']); ?></td>
                    <td><?php echo $this->escape($form['time_start_view']); ?></td>
                    <td><?php echo $this->escape($form['time_end_view']); ?></td>
                    <td><?php echo $form['register_need'] ? __('Yes') : __('No'); ?></td>
                    <td>


                        <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['action' => 'update', 'id' => $form['id']]); ?>">
                            <i class="fa fa-edit"></i> <?php _e('Edit'); ?>
                        </a>
                        <a class="btn btn-primary btn-sm" title="<?php _e('Element'); ?>"
                           href="<?php echo $this->url('', ['action' => 'element', 'id' => $form['id']]); ?>">
                            <i class="fa fa-edit"></i> <?php _e('Element'); ?>
                        </a>



                        <a class="btn btn-success btn-sm" title="<?php _e('View'); ?>"
                           href="<?php echo $this->url('', ['action' => 'view', 'id' => $form['id']]); ?>">
                            <i class="fa fa-eye"></i> <?php _e('View'); ?>
                        </a>
                        <a class="btn btn-success btn-sm" title="<?php _e('View on front'); ?>"
                           href="<?php echo $this->url(
                               'default', [
                                   'module'     => 'forms',
                                   'controller' => 'index',
                                   'action'     => 'view',
                                   'slug'       => $form['slug'],
                               ]
                           ); ?>" target="_blank">
                            <i class="fa fa-eye"></i> <?php _e('View on front'); ?>
                        </a>


                        <a class="btn btn-warning btn-sm" title="<?php _e('Record'); ?>"
                           href="<?php echo $this->url('', ['controller' => 'record', 'selectForm' => $form['id']]); ?>">
                            <i class="fa fa-eye"></i> <?php _e('Record'); ?>
                        </a>
                        <a class="btn btn-warning btn-sm" title="<?php _e('Export Record'); ?>"
                           href="<?php echo $this->url('', ['controller' => 'record','action' => 'export', 'selectForm' => $form['id']]); ?>">
                            <i class="fa fa-eye"></i> <?php _e('Export Record'); ?>
                        </a>


                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('You still didnt make any form, please make new one'); ?>
        </div>
    <?php } ?>
</div>
