<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php _e('List of records'); ?></h3>
    <?php if (!empty($list)) { ?>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Form'); ?></th>
                <th><?php _e('Extra'); ?></th>
                <th><?php _e('User'); ?></th>
                <th><?php _e('Time'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $record) { ?>
                <tr>
                    <td><?php echo $this->escape($record['id']); ?></td>
                    <td><?php echo $this->escape($record['form']['title']); ?></td>
                    <td><?php echo $this->escape($record['extra_key']); ?></td>
                    <td><?php echo $this->escape($record['user']['name']); ?>
                        ( <?php echo $this->escape($record['user']['email']); ?> )
                    </td>
                    <td><?php echo $this->escape($record['time_create_view']); ?></td>
                    <td>
                        <a class="btn btn-success btn-xs" title="<?php _e('View'); ?>"
                           href="<?php echo $this->url('', ['action' => 'view', 'id' => $record['id']]); ?>"><i
                                    class="fa fa-edit"></i> <?php _e('View'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php _e('On record saved on system'); ?>
        </div>
    <?php } ?>
</div>