<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <table class="table table-striped table-bordered table-hover table-responsive-md table-sm mt-3">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Form'); ?></th>
            <th><?php _e('Extra'); ?></th>
            <th><?php _e('User'); ?></th>
            <th><?php _e('Time'); ?></th>
        </tr>
        <tr>
            <td><?php echo $this->escape($record['id']); ?></td>
            <td><?php echo $this->escape($record['form']['title']); ?></td>
            <td><?php echo $this->escape($record['extra_key']); ?></td>
            <td><?php echo $this->escape($record['user']['name']); ?>( <?php echo $this->escape($record['user']['email']); ?> )</td>
            <td><?php echo $this->escape($record['time_create_view']); ?></td>
        </tr>
    </table>

    <table class="table table-striped table-bordered table-hover table-responsive-md table-sm mt-3">
        <tr>
            <th><?php _e('Element'); ?></th>
            <th><?php _e('Value'); ?></th>
            <th><?php _e('Element type'); ?></th>
        </tr>
        <?php foreach ($record['data'] as $data) { ?>
            <tr>
                <td><?php echo $this->escape($data['element_title']); ?></td>
                <td><?php echo $this->escape($data['value']); ?></td>
                <td><?php echo $this->escape($data['element_type']); ?></td>
            </tr>
        <?php } ?>
    </table>
</div>
