<?php if (isset($selectForm) && $selectForm) { ?>
    <?php if (!empty($selectForm['description'])) { ?>
        <div class="clearfix form-description">
            <?php echo $selectForm['description']; ?>
        </div>
    <?php } ?>
    <?php echo $this->form($form); ?>
<?php } else { ?>
    <h1><?php echo $this->escape($selectForm['title']); ?></h1>
    <p>شما قبلا این فرم را تکمیل کرده اید یا دسترسی برای تکمیل آن ندارید</p>
    <p>
        <a class="btn btn-secondary" href="https://www.orodmarketing.com/apis/forms/back">برگشت</a>
    </p>
<?php } ?>