<?php
$this->css($this->assetModule('css/front.css'));
switch (count($forms)) {
    case 1:
        $formClass = 'col-md-12';
        break;

    case 2:
        $formClass = 'col-md-6';
        break;

    case 3:
    case 6:
    case 9:
        $formClass = 'col-md-4';
        break;

    case 4:
    case 8:
    case 12:
        $formClass = 'col-md-3';
        break;

    default:
        $formClass = 'col-md-4';
        break;
}
?>
<div class="clearfix row user-section-wrapper">
    <div class="col-md-3">
        <?php $sideActive = 'forms'; ?>
        <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
    </div>
    <div class="col-md-9">
        <?php include $this->template('flash-messenger'); ?>
        <div class="mb-4">
            <h1><?php _e('List of available forms'); ?></h1>
        </div>
        <?php if (!empty($forms)) { ?>
            <div class="row clearfix">
                <?php foreach ($forms as $form) { ?>
                    <div class="<?php echo $formClass; ?>">
                        <div class="card">
                            <?php if (!is_null($form['main_image'])) { ?>
                                <img src="<?php echo (string)Pi::api('doc', 'media')->getSingleLinkUrl($form['main_image'])->thumb(400, 300); ?>"
                                     class="card-img-top" alt="<?php echo $this->escape($form['title']); ?>">
                            <?php } ?>
                            <div class="card-body">
                                <h5 class="card-title"><?php echo $this->escape($form['title']); ?></h5>
                                <?php if (!empty($form['description'])) { ?>
                                    <div class="card-text">
                                        <?php echo $form['description']; ?>
                                    </div>
                                <?php } ?>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    <?php _e('From'); ?> : <?php echo $this->escape($form['time_start_view']); ?>
                                </li>
                                <li class="list-group-item">
                                    <?php _e('To'); ?> : <?php echo $this->escape($form['time_end_view']); ?>
                                </li>
                            </ul>
                            <div class="card-body">
                                <a href="<?php echo $this->escape($form['formUrl']); ?>" class="card-link">
                                    <?php _e('Fill the form'); ?>
                                </a>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>
        <?php } ?>
        <?php if (!empty($records)) { ?>
            <div class="mt-4 mb-4">
                <h1><?php _e('Your input recodes'); ?></h1>
            </div>
            <table class="table table-striped table-bordered table-sm">
                <tr>
                    <th class="text-center"><?php _e('Id'); ?></th>
                    <th class="text-center"><?php _e('Time'); ?></th>
                    <th class="text-center"><?php _e('Form'); ?></th>
                    <th class="text-center"><?php _e('Action'); ?></th>
                </tr>
                <?php foreach ($records as $record) { ?>
                    <tr>
                        <td class="text-center"><?php echo $this->escape($record['id']); ?></td>
                        <td class="text-center"><?php echo $this->escape($record['time_create_view']); ?></td>
                        <td class="text-center"><?php echo $this->escape($record['title']); ?></td>
                        <td class="text-center"></td>
                    </tr>
                <?php } ?>
            </table>
        <?php } ?>
    </div>
</div>
