<?php
$this->css($this->assetModule('css/front.css'));
switch (count($forms)) {
    case 1:
        $formClass = 'col-md-12';
        break;

    case 2:
        $formClass = 'col-md-6';
        break;

    case 3:
    case 6:
    case 9:
        $formClass = 'col-md-4';
        break;

    case 4:
    case 8:
    case 12:
        $formClass = 'col-md-3';
        break;

    default:
        $formClass = 'col-md-4';
        break;
}
?>
<div class="clearfix row user-section-wrapper">
    <?php if (Pi::user()->hasIdentity()) { ?>
        <div class="col-lg-3 col-md-3 col-12">
            <?php $sideActive = 'forms'; ?>
            <?php include $this->templateModule('front/user-profile-sidebar.phtml', 'user'); ?>
        </div>
    <?php } ?>
    <div class="<?php if (Pi::user()->hasIdentity()) { ?>col-lg-9 col-md-9 col-12<?php } else { ?>col-lg-12 col-md-12 col-12<?php } ?>">
        <div class="mb-3">
            <h1><?php _e('List of available forms'); ?></h1>
        </div>
        <?php if (isset($forms) && !empty($forms)) { ?>
            <div class="row clearfix mb-3">
                <?php foreach ($forms as $form) { ?>
                    <div class="<?php echo $formClass; ?>">
                        <div class="card mb-3">
                            <?php if (isset($form['image_information']) && !empty($form['image_information'])) { ?>
                                <img class="card-img-top" src="<?php echo $this->escape($form['image_information']['resized_url']); ?>"
                                     alt="<?php echo $this->escape($form['image_information']['title']); ?><?php if ($form['image_information']['copyright']) echo ' - ' . $form['image_information']['copyright'] ?>">
                            <?php } ?>
                            <div class="card-body">
                                <h4 class="card-title"><?php echo $this->escape($form['title']); ?></h4>
                                <?php if (!empty($form['description'])) { ?>
                                    <div class="card-text clearfix">
                                        <?php echo $form['description']; ?>
                                    </div>
                                <?php } ?>

                                <a href="<?php echo $this->escape($form['formUrl']); ?>" class="card-link">
                                    <?php _e('View and fill the form'); ?>
                                </a>
                            </div>
                        </div>
                    </div>
                <?php } ?>
            </div>
        <?php } else { ?>
            <div class="alert alert-danger mb-3">
                <?php _e('No active form available'); ?>
            </div>
        <?php } ?>
    </div>
</div>
