<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="clearfix">
    <?php if (isset($records) && !empty($records)) { ?>
        <div class="mb-3">
            <h1><?php _e('Your input recodes'); ?></h1>
        </div>
        <table class="table table-striped table-bordered table-hover table-responsive-md table-sm mt-3">
            <tr>
                <th class="text-center"><?php _e('ID'); ?></th>
                <th class="text-center"><?php _e('Time'); ?></th>
                <th class="text-center"><?php _e('Form'); ?></th>
                <th class="text-center"><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($records as $record) { ?>
                <tr>
                    <td class="text-center"><?php echo $this->escape($record['id']); ?></td>
                    <td class="text-center"><?php echo $this->escape($record['time_create_view']); ?></td>
                    <td class="text-center"><?php echo $this->escape($record['title']); ?></td>
                    <dt class="text-center"></dt>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger">
            <?php _e('You dont put any entry on our forms yet !'); ?>
        </div>
    <?php } ?>
</div>
